name: Portfolio CD # Название workflow (процесса автоматизации)

on:
  push:
    branches: [ main ] # Триггер: запускать workflow при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest # Определение окружения: используется последняя версия Ubuntu

    steps:
    - name: Deploy using ssh # Название шага: Деплой с использованием SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
        # host: ${{ secrets.HOST }} # Хост (сервер) для подключения, берется из секретов Github
        # username: ${{ secrets.USERNAME }} # Имя пользователя для SSH, берется из секретов Github
        # key: ${{ secrets.PRIVATE_KEY }} # Приватный ключ для SSH, берется из секретов Github
        # port: 22 # Порт для SSH-подключения (по умолчанию 22)
        # script: |
          # su - etten
          # cd portfolio/portfolio 
          # git pull origin main 
          # git status
          # npm install 
          # npm run build
          # pm2 restart all 
